version: '3.8'

services:
  database:
    container_name: cars-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: cars-php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../api:/var/www/docker
    depends_on:
      - database
  nginx:
    container_name: cars-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../api:/var/www/docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
